FROM star-base

WORKDIR /tmp

# Get the latest STAR software
RUN git clone https://gitlab.com/star-bnl/star-sw.git \
 && git clone https://gitlab.com/star-bnl/star-cvs.git

# Build and install STAR software
WORKDIR /tmp/star-build
RUN cmake /tmp/star-sw -DSTAR_SRC=/tmp/star-cvs -DSTAR_PATCH=gcc540 -DCMAKE_INSTALL_PREFIX=/tmp/star-install -DCERNLIB_ROOT=/cern/2006 -DCMAKE_BUILD_TYPE=Debug \
 && make -j $(nproc) \
 && make install

WORKDIR /tmp/star-install
